update llvmlite to 0.30.0 (#31858)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/31858

Trying to upgrade docker image but ran into the following error:

```
Running test_nn ... [2020-01-04 18:05:12.537860]
Traceback (most recent call last):
  File "test_nn.py", line 45, in <module>
    from common_cuda import TEST_CUDA, TEST_MULTIGPU, TEST_CUDNN, TEST_CUDNN_VERSION
  File "/var/lib/jenkins/workspace/test/common_cuda.py", line 16, in <module>
    import numba.cuda
  File "/opt/conda/lib/python3.6/site-packages/numba/__init__.py", line 178, in <module>
    _ensure_llvm()
  File "/opt/conda/lib/python3.6/site-packages/numba/__init__.py", line 100, in _ensure_llvm
    raise ImportError(msg)
ImportError: Numba requires at least version 0.30.0 of llvmlite.
Installed version is 0.28.0.
```

Test Plan: Imported from OSS

Differential Revision: D19282923

Pulled By: ljk53

fbshipit-source-id: bdeefbf4f6c0c97df622282f76e77eb1eadba436