[FX] Fix type of argument min_acc_module_size (#74891)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/74891

As title, otherwise the below error is thrown:
```
TypeError: '>=' not supported between instances of 'int' and 'str'
```

Test Plan: easy

Reviewed By: jackm321

Differential Revision: D35206473

fbshipit-source-id: 200c83b9a19b6aae6f0da03abe99121e55893fd3
(cherry picked from commit 20744d2ce59ea07ecdb2570929dd5344c65b751a)