ci: Bump TorchAudio, less third_party deps (#114393)
Installing the current pinned version of TorchAudio can be problematic because it
expects to be able to download a file from sourceware.org (see [ref](https://github.com/pytorch/audio/blob/a8f4e97bd5356a7a77510cdf6a3a62e25a5dc602/third_party/bzip2/CMakeLists.txt#L14)) and that does
not have any guarantees of uptime.

This bumps this commit to the latest v2.1.1 commit (https://github.com/pytorch/audio/releases/tag/v2.1.1) which should have less third_party dependencies and thus be less flaky

<details>

<summary> Should help with errors like: </summary>

logs link: https://github.com/pytorch/pytorch/actions/runs/6959510046/job/18942955523#step:15:592

```
5h+ pip install --progress-bar off --no-use-pep517 --user git+https://github.com/pytorch/audio.git@a8f4e97bd5356a7a77510cdf6a3a62e25a5dc602
Collecting git+https://github.com/pytorch/audio.git@a8f4e97bd5356a7a77510cdf6a3a62e25a5dc602
  Cloning https://github.com/pytorch/audio.git (to revision a8f4e97bd5356a7a77510cdf6a3a62e25a5dc602) to /tmp/pip-req-build-6b5hkzmq
  Running command git clone --filter=blob:none --quiet https://github.com/pytorch/audio.git /tmp/pip-req-build-6b5hkzmq
  Running command git rev-parse -q --verify 'sha^a8f4e97bd5356a7a77510cdf6a3a62e25a5dc602'
  Running command git fetch -q https://github.com/pytorch/audio.git a8f4e97bd5356a7a77510cdf6a3a62e25a5dc602
  Running command git checkout -q a8f4e97bd5356a7a77510cdf6a3a62e25a5dc602
  Resolved https://github.com/pytorch/audio.git to commit a8f4e97bd5356a7a77510cdf6a3a62e25a5dc602
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... 25l- error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]
      Traceback (most recent call last):
        File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
          h.request(req.get_method(), req.selector, req.data, headers,
        File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 1283, in request
          self._send_request(method, url, body, headers, encode_chunked)
        File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 1329, in _send_request
          self.endheaders(body, encode_chunked=encode_chunked)
        File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 1278, in endheaders
          self._send_output(message_body, encode_chunked=encode_chunked)
        File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 1038, in _send_output
          self.send(msg)
        File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 976, in send
          self.connect()
        File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 1448, in connect
          super().connect()
        File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 942, in connect
          self.sock = self._create_connection(
        File "/opt/conda/envs/py_3.10/lib/python3.10/socket.py", line 845, in create_connection
          raise err
        File "/opt/conda/envs/py_3.10/lib/python3.10/socket.py", line 833, in create_connection
          sock.connect(sa)
      OSError: [Errno 99] Cannot assign requested address

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-6b5hkzmq/setup.py", line 184, in <module>
          _main()
        File "/tmp/pip-req-build-6b5hkzmq/setup.py", line 145, in _main
          _fetch_third_party_libraries()
        File "/tmp/pip-req-build-6b5hkzmq/setup.py", line 129, in _fetch_third_party_libraries
          _fetch_archives(_parse_sources())
        File "/tmp/pip-req-build-6b5hkzmq/setup.py", line 123, in _fetch_archives
          torch.hub.download_url_to_file(url, dest, progress=False)
        File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/hub.py", line 620, in download_url_to_file
          u = urlopen(req)
        File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
          return opener.open(url, data, timeout)
        File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 519, in open
          response = self._open(req, data)
        File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 536, in _open
          result = self._call_chain(self.handle_open, protocol, protocol +
        File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
          result = func(*args)
        File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
          return self.do_open(http.client.HTTPSConnection, req,
        File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
          raise URLError(err)
      urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
      -- Git branch: HEAD
      -- Git SHA: a8f4e97bd5356a7a77510cdf6a3a62e25a5dc[602](https://github.com/pytorch/pytorch/actions/runs/6959510046/job/18942955523#step:15:603)
      -- Git tag: None
      -- PyTorch dependency: torch
      -- Building version 2.0.0a0+a8f4e97
       --- Initializing submodules
       --- Initialized submodule
       --- Fetching v1.2.12.tar.gz
       --- Fetching bzip2-1.0.8.tar.gz
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

</details>

Signed-off-by: Eli Uriegas <eliuriegas@meta.com>
Pull Request resolved: https://github.com/pytorch/pytorch/pull/114393
Approved by: https://github.com/atalman, https://github.com/kit1980, https://github.com/huydhn