add sndfile yum package to centos dockerfile (#54687)
Summary:
Fixes error when running torch test suite inside a centos CI image.  As described by https://pypi.org/project/SoundFile/0.10.3.post1/, `On Linux, you need to install libsndfile using your distribution’s package manager`.  This was missing from the centos CI image.

```
python test_spectral_ops.py -v
...
Traceback (most recent call last):
  File "test_spectral_ops.py", line 25, in <module>
    import librosa
  File "/opt/conda/lib/python3.6/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/opt/conda/lib/python3.6/site-packages/librosa/core/__init__.py", line 6, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/opt/conda/lib/python3.6/site-packages/librosa/core/audio.py", line 8, in <module>
    import soundfile as sf
  File "/opt/conda/lib/python3.6/site-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found
```

Pull Request resolved: https://github.com/pytorch/pytorch/pull/54687

Reviewed By: ezyang

Differential Revision: D27332975

Pulled By: walterddr

fbshipit-source-id: 9c6b37545e9f2536c83e606912859439847c884a