Move bazel and xla to unstable (#93296)
Fixes #ISSUE_NUMBER
currently they are failing due things like
```

ERROR: An error occurred during the fetch of repository 'tf_runtime':
   Traceback (most recent call last):
	File "/var/lib/jenkins/workspace/xla/third_party/tensorflow/third_party/repo.bzl", line 73, column 33, in _tf_http_archive_impl
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/3367783466dff91b8b283d61c7fe8abc9e7bbb80.tar.gz, https://github.com/tensorflow/runtime/archive/3367783466dff91b8b283d61c7fe8abc9e7bbb80.tar.gz] to /home/jenkins/.cache/bazel/_bazel_jenkins/b463291cb8b07b4bfde1e3a43733cd1a/external/tf_runtime/temp17509854002229755553/3367783466dff91b8b283d61c7fe8abc9e7bbb80.tar.gz: Checksum was 4d2fc38d8b6edd1a478ea2fcb88491eeaf7378e5ffe9f4e3eb3b821df1d1c5ba but wanted 5e6bab71ce31b4b56105ac4567f8bffa5f5b3de7ad3064638297249e69375623
```
so I move to unstable until we investigate and fix
Pull Request resolved: https://github.com/pytorch/pytorch/pull/93296
Approved by: https://github.com/huydhn