Minor update to ROCm triton commit pin (#106616)
This is required for a fix in latest nightly wheels in which the hip_runtime header file cannot be found during triton lowering

```
/tmp/tmpqoq6gtl8/main.c:3:14: fatal error: hip/hip_runtime.h: No such file or directory
3 | #include <hip/hip_runtime.h>
| ^~~~~~~~~~~~~~~~~~~
```

This is a single commit update to bring in this change
https://github.com/ROCmSoftwarePlatform/triton/pull/283

Pull Request resolved: https://github.com/pytorch/pytorch/pull/106616
Approved by: https://github.com/malfet