Fix AttributeError: 'int' object has no attribute 'node' due to constant prop (#141250)
Fixes https://github.com/pytorch/pytorch/issues/140625

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

Pull Request resolved: https://github.com/pytorch/pytorch/pull/141250
Approved by: https://github.com/bobrenjc93