Support converting Python number to IValue in pybind_utils.h (#22817)
Summary:
I ran into the following error when trying to pass a Python int as an arg to `torch::jit::createStackForSchema`, and I think it is due to the missing support for `NumberType` in [toIValue](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/pybind_utils.h#L448).

> RuntimeError: Missing cases in toIValue for type: Scalar! File a bug report. (toIValue at ../torch/csrc/jit/pybind_utils.h:449)
Pull Request resolved: https://github.com/pytorch/pytorch/pull/22817

Differential Revision: D16276006

Pulled By: mrshenli

fbshipit-source-id: 7f63519bb37219445e836ec1f51ca4f98bf52c44